// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TinyTranslation.EFStore.Data;

namespace TranslationWeb.Migrations.TranslationDb
{
    [DbContext(typeof(TranslationDbContext))]
    partial class TranslationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TinyTranslation.EFStore.Data.Models.Locale", b =>
                {
                    b.Property<int>("LocalID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key");

                    b.HasKey("LocalID");

                    b.ToTable("Locales");
                });

            modelBuilder.Entity("TinyTranslation.EFStore.Data.Models.Translation", b =>
                {
                    b.Property<int>("TranslationID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key");

                    b.Property<int>("LocalID");

                    b.Property<string>("Value");

                    b.HasKey("TranslationID");

                    b.ToTable("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
